config/routes.rb
Cjproject::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
   get 'signout', to: 'sessions#destroy', as: 'signout'
 
  resources :games do
    member do
      post 'play'
      post 'roll'
      post 'roll_other'
      post 'select'
    end
  end

  root 'games#index'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  def from_jamb(jamb)
    self.jambgame = jamb.to_game_string  #  Marshal.dump(jamb)
  end
  def to_jamb
    j = Jamb.new
    j.from_game_string(self.jambgame)
    j
#    Marshal.load(self.jambgame)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    game = Game.find(params[:id])
    @jamb = game.to_jamb
    gon.user_name = current_user.name
  end
  
  def index
    
  end 
 
  def create
    @jamb = Jamb.new
    game = Game.new
    game.user_id = current_user.id
    game.from_jamb(@jamb)
    game.save!
    redirect_to game_path(game.id)
   end
  
  def select
    game = Game.find(params[:id])
    @jamb = game.to_jamb
    if [:first_roll,:second_roll].include?(@jamb.diceboard.mode) 
      @selected = params[:dice].to_i
      @jamb.diceboard.toggle(@selected)
      game.from_jamb(@jamb)
      game.save!
    end
    respond_to do |format|
      format.html { redirect_to game_path(game.id)}
      format.js 
    end
    
  end 

  def roll
    game = Game.find(params[:id])
    @jamb = game.to_jamb
    @jamb.diceboard.roll_selected
    game.from_jamb(@jamb)
    game.save!
    @changed = @jamb.diceboard.changed
    respond_to do |format|
      format.html {redirect_to game_path(game.id)}
      format.js
    end
  end  

  def roll_other 
    game = Game.find(params[:id])
    @jamb = game.to_jamb
    @jamb.diceboard.roll_unselected
    game.from_jamb(@jamb)
    game.save!
    @changed = @jamb.diceboard.changed
    respond_to do |format|
      format.html { redirect_to game_path(game.id) }
      format.js { render 'roll.js' }
    end  
  end  

  def play
    game = Game.find(params[:id])
    game_playround = params[:playround].to_i
    @jamb = game.to_jamb
    @jamb.play(params[:row].to_i,params[:col].to_i)
    game.from_jamb(@jamb)
    game.save!
    if @jamb.diceboard.mode == :end_game
      UserStat.add_score(current_user.id,@jamb.end_game_score)
      Oldgame.save_new(game,@jamb.end_game_score)
      Game.destroy(game.id)
    end
    respond_to do |format|
      format.html { redirect_to game_path(game.id) }
      format.js
    end
  end  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/.#_userindex.html.erb
braca@bvm.14008:1376647300

app/views/games/_cell.html.erb
<% if @jamb.cell(row,col).is_enabled? %>
  <%= content_tag :td ,  link_to("___ ", play_game_path( :row => row , :col=>col,:playround => @jamb.playround ),:method => :post,:remote => true  )  , :class => @jamb.cell(row,col).class_str,:id => @jamb.cell_id(row,col)  %>	  <% else %>
	    <%= content_tag :td ,  @jamb.cell(row,col).value , :class => @jamb.cell(row,col).class_str,:id => @jamb.cell_id(row,col)  %>	 
          <% end %>

app/views/games/_dice.html.erb
<span class="any_dice">
<%= link_to select_game_path(:dice => dice ) , :id => "select_dice_link#{dice}", :method => :post , :remote => true do %>
  <%= image_tag @jamb.diceboard.img(dice) , :id => "dice#{dice}", :class => @jamb.diceboard.class_str(dice) %>  
<%end%>  
</span>

app/views/games/_diceboard_status.html.erb
<%= "Dices #{@jamb.diceboard.dices}" %>
<%= "Mode #{@jamb.diceboard.mode}" %>
<%= "Selected: #{@jamb.diceboard.selected}" %>
<%= "Changed: #{@jamb.diceboard.changed}" %>  
<%= "Playround: #{@jamb.playround}" %>

app/views/games/_diceimg.html.erb
<%= image_tag @jamb.diceboard.img(dice) , :id => "dice#{dice}", :class => @jamb.diceboard.class_str(dice) %>  

app/views/games/_dices.html.erb
<span id="dices">   
<% (0..4).each do |dice| %>
  <%= render partial: "dice", locals: { dice: dice} %>  
<% end %>
</span>

app/views/games/_roll_button.html.erb
<span id="roll_button">
  <%= link_to roll_game_path(:playroud => @jamb.playround),  { :method=>:post, :class =>  "btn btn-primary btn-large play",:remote => true } do %>
    <i class="icon-white icon-hand-right"></i> &nbsp <%= @jamb.diceboard.mode.to_sym == :no_roll ? "Roll" :  "Roll selected dices" %></i>
  <% end %>
</span>
    

app/views/games/_roll_other.html.erb
<span id="roll_other_button">
  <%= link_to roll_other_game_path(:playround => @jamb.playround) ,  { :method=>:post, :class =>  "btn btn-primary btn-large play", :remote => true } do %>
    <i class="icon-white icon-hand-left"></i> &nbsp  <%=  "Roll unselected dices" %> </i>
  <% end %>
</span>  

app/views/games/_table.html.erb
<table id="jtable" class="table table-bordered table-game">
  <% @jamb.rows do |row| %>
    <%  if row == 0  %>
	<thead><tr>
    <% else %> 
	<tr>
    <% end %>
    <% @jamb.columns do |col| %>
	<% if col == 0 %>
	  <%= content_tag :th , @jamb.cell(row,col).value , :class => @jamb.cell(row,col).class_str, :id => @jamb.cell_id(row,col) %>	
    <% else %> 
	  <%= render partial: 'cell', locals: { row: row, col: col }  %>
     <% end %>
    <% end %>

    <%  if row == 0  %>
	</tr></thead><tbody>
    <% else %> 
	</tr>
    <% end %>

  <% end %>   
   </tbody>
</table>

app/views/games/_userstat.html.erb
<% if current_user %> 
     <div id="stat">   
       <h4> Your stat </h4>
       <ul class="list-group">
       <li class="list-group-item">
         <span class="badge pull-right"><%="#{UserStat.user_last_score(current_user.id.to_s)}" %> </span>
         <%= "Last score" %>
       </li>
       <li class="list-group-item">
	 <span class= "badge pull-right"> <%= "#{UserStat.user_average(current_user.id.to_s).to_i}" %> </span>
         <%= "Average score: " %> 
       </li>
       <li class="list-group-item">
          <span class= "badge pull-right"><%="#{UserStat.user_games_played(current_user.id.to_s)}" %> </span>
          <%= "Games Played:" %>
       </li>
       <li class="list-group-item">
	 <span class= "badge pull-right"><%="#{UserStat.user_games_best(current_user.id.to_s)}" %> </span>
         <%= "Best Game:" %>
       </li>
       </ul>
     </div>
<% end %>

app/views/games/index.html.erb
<% content_for :home do %>
 <div id="home" class = "jumbotron"  %> 
   <% if current_user %>
     <%= render partial: 'userindex' %>
   <%else%>    
     <h2><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn btn-primary btn-lg" %></h2>
   <%end%>  
 </div>
<% end %>

<% content_for :yourstat do %> 
 <div id="indexyourstat">
   <h3> Your stat </h3>
  <% if current_user %>      
     <table id="imgstat"> 
       <tr class="bsrow"   >
         <td class="bscores" >
         <ul id = "bestuserstat">
           <li><i class="icon-white icon-cloud"></i>&nbsp<%= "Average: #{UserStat.user_average(current_user.id.to_s)}" %> </li> 
           <li><i class="icon-white icon-bell"></i>&nbsp<%= "Best : #{UserStat.user_games_best(current_user.id.to_s)}" %> </li> 
           <li><i class="icon-white icon-signal"></i>&nbsp<%= "Games played: #{UserStat.user_games_played(current_user.id.to_s)}" %></li> 
        </ul>
        <td>
       </tr>
     </table>
  <%else%>
    Please login to see your stat  
  <%end%>
 </div>
<%end%>  

<% content_for :bestscores do %>
  <div id="indexuserstat">
    <h3> Best players </h3>
   <ul id = "bestlist" > 
   <% GamesStat.best_scores.each do |user|  %> 
   <li>
     <table id="imgstat"> 
      <tr class="bsrow"   >  
	<td class="imgtd"><%= image_tag( user.image, class: "bsimage"  ) %><br/><strong><%= user.name %></strong></td>
        <td class="bscores" ><ul id = "bestuserstat">
               <li><i class="icon-white icon-cloud"></i>&nbsp<%= "Average: #{UserStat.user_average(user.id.to_s)}" %> </li> 
               <li><i class="icon-white icon-bell"></i>&nbsp<%= "Best : #{UserStat.user_games_best(user.id.to_s)}" %> </li> 
               <li><i class="icon-white icon-signal"></i>&nbsp<%= "Games played: #{UserStat.user_games_played(user.id.to_s)}" %> 
        </ul></td></tr></table> 
   </li>
   <%end%>
   </ul>  
  </div>
<%end%>

<% content_for :gamestats do %>
  <div id="gamestats">
    <h3> Game stat </h3>
    <table id="imgstat"> 
       <tr class="bsrow"   >
         <td class="bscores" >
         <ul id = "bestuserstat">
           <li><i class="icon-white icon-signal"></i>&nbsp<%= "Games played : #{GamesStat.games_played}" %> </li> 
           <li><i class="icon-white icon-cloud"></i>&nbsp<%= "Average score : #{GamesStat.all_user_average}" %> </li> 
           <li><i class="icon-white icon-bell"></i>&nbsp<%= "Best score : #{GamesStat.best}" %> </li> 
        </ul>
        <td>
       </tr>
     </table>
  </div>
<%end%>

app/views/games/play.js.erb
var changed = <%=raw @jamb.changed.to_json %>;
var i=0;
<% @jamb.changed.each do |cell| %>
    var idx = "#" + changed[i][0] + "a" + changed[i][1];
    $(idx).replaceWith("<%= j render partial: 'cell', locals: { row: cell[0], col: cell[1] } %>");
    i++;
<%end%>



<% if @jamb.diceboard.mode != :end_game %>   
  $("#dices").replaceWith("<%= j render partial: 'dices' %>");
  $("#roll_buttons").children().remove();
  $("#roll_buttons").append("<%= j render partial: 'buttons' %>"); 
<%else%>
  $("#diceboard").replaceWith("<%=j render partial: 'end_game' %>");
<%end%>  
$("#diceboardstatus").html("<%= j render partial: 'diceboard_status' %>");

app/views/games/select.js.erb
$("<%= j "#dice#{@selected}" %>").removeClass();
$("<%= j "#dice#{@selected}" %>").addClass("<%= j @jamb.diceboard.class_str(@selected)%>");
$("#diceboardstatus").html("<%= j render partial: 'diceboard_status' %>");

app/views/games/show.html.erb
<% content_for :table do %>
 <%= render partial: "table"%>
<%end%>

<% content_for :userstat do %>
  <%= render partial: "userstat" %>  
<%end%>

<% content_for :userinfo do %>
 <div id="testdice0" class="animdice"></div>
 <div id="testdice1" class="animdice"></div>
 <div id="testdice2" class="animdice"></div>
 <div id="testdice3" class="animdice"></div>
 <div id="testdice4" class="animdice"></div>
  <%= render partial: "userinfo" %>
<%end%>

<% content_for :diceboard do%>
 
  <% if @jamb.diceboard.mode != :end_game %>   
    <div id='diceboard'>
      <%= render partial: "dices" %><br/><br/>
      <span id="roll_buttons">
        <%= render partial: "buttons" %>
      </span>
    </div>
  <% else %>
      <%= render partial: "end_game" %>
  <% end %>
<%end%>

<% content_for :jscripts do %>
<%end%>